# Generated by Django 5.0.7 on 2024-08-31 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='admins',
        ),
    ]
