# Generated by Django 5.0.7 on 2024-08-31 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_admin_admins'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admins',
            new_name='admin_data',
        ),
    ]
