# Generated by Django 5.0.7 on 2024-08-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_employee_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='is_salary_calculated',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
