# Generated by Django 5.0.7 on 2024-08-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_salary_is_salary_calculated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='overtime',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salary',
            name='total_leave_taken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salary',
            name='total_working_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
