# Generated by Django 5.0.7 on 2024-08-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_salary_overtime_alter_salary_total_leave_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='Total_salary_made',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
