# Generated by Django 5.0.7 on 2024-09-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_cartitem_cart_reviewed_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewed_product',
            name='products',
        ),
        migrations.AddField(
            model_name='reviewed_product',
            name='product',
            field=models.ManyToManyField(default=' ', to='app1.product'),
        ),
    ]
