# Generated by Django 5.0.7 on 2024-09-12 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_order_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_address',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.order'),
            preserve_default=False,
        ),
    ]
