# Generated by Django 5.0.7 on 2024-09-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_order_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetail',
            name='customer',
        ),
    ]
