# Generated by Django 5.0.7 on 2024-09-20 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_entry_transaction_detail_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='static/image/default-user.png', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='Wallet_amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
