# Generated by Django 5.0.7 on 2024-09-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='Wallet_amount',
            field=models.FloatField(default='0'),
        ),
    ]
