# Generated by Django 5.0.7 on 2024-09-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_transaction_detail_date_of_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_detail',
            name='payment_id',
            field=models.CharField(default='na', max_length=100),
            preserve_default=False,
        ),
    ]
