# Generated by Django 5.0.7 on 2024-09-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_transaction_detail_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_detail',
            name='payment_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
