# Generated by Django 5.0.7 on 2024-08-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_admins_modeladmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelAdmin',
        ),
        migrations.AddField(
            model_name='post',
            name='block_status',
            field=models.BooleanField(default=False),
        ),
    ]
